// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sovmobytkxcmseetlynt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdm1vYnl0a3hjbXNlZXRseW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzMxMTAsImV4cCI6MjA3MDUwOTExMH0.8NTEfbIzBR-P6QMrk9R9AHQGALfNVF24IAaOxJRT7ZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});